# Generated by Django 5.1.3 on 2024-11-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
