from django.core.management import BaseCommand

from sacco.models import Customer


class Command(BaseCommand):
    help = 'Populates database with data'
    def handle(self, *args, **options):
        customers = [{"first_name":"Justen","last_name":"Cammidge","email":"jcammidge0@illinois.edu","gender":"Male","dob":"2002-12-16","weight":69},
{"first_name":"Rufe","last_name":"Vasyaev","email":"rvasyaev1@liveinternet.ru","gender":"Male","dob":"2005-01-24","weight":40},
{"first_name":"Meggie","last_name":"Floodgate","email":"mfloodgate2@biblegateway.com","gender":"Female","dob":"1996-04-05","weight":58},
{"first_name":"Wiatt","last_name":"Shalloe","email":"wshalloe3@comsenz.com","gender":"Male","dob":"2004-05-04","weight":84},
{"first_name":"Natalya","last_name":"Coulthart","email":"ncoulthart4@walmart.com","gender":"Female","dob":"1996-06-07","weight":88},
{"first_name":"Jocko","last_name":"Skipworth","email":"jskipworth5@alibaba.com","gender":"Male","dob":"2001-08-02","weight":53},
{"first_name":"Idette","last_name":"Downes","email":"idownes6@jiathis.com","gender":"Female","dob":"2002-05-22","weight":45},
{"first_name":"Noelle","last_name":"Platfoot","email":"nplatfoot7@newyorker.com","gender":"Male","dob":"2004-08-10","weight":80},
{"first_name":"Amy","last_name":"Pellingar","email":"apellingar8@mysql.com","gender":"Female","dob":"1999-01-23","weight":72},
{"first_name":"Baillie","last_name":"Stolli","email":"bstolli9@networksolutions.com","gender":"Male","dob":"1998-10-06","weight":56},
{"first_name":"Felipe","last_name":"Hacket","email":"fhacketa@nifty.com","gender":"Male","dob":"1997-07-11","weight":75},
{"first_name":"Benedikta","last_name":"Vergine","email":"bvergineb@pbs.org","gender":"Female","dob":"2001-04-20","weight":83},
{"first_name":"Ogdan","last_name":"O'Hederscoll","email":"oohederscollc@nba.com","gender":"Male","dob":"1997-12-09","weight":87},
{"first_name":"Stefa","last_name":"Carradice","email":"scarradiced@naver.com","gender":"Female","dob":"2004-01-17","weight":85},
{"first_name":"Sean","last_name":"Fermer","email":"sfermere@live.com","gender":"Male","dob":"2001-07-01","weight":88},
{"first_name":"Arvin","last_name":"Sheepy","email":"asheepyf@freewebs.com","gender":"Male","dob":"1998-07-17","weight":60},
{"first_name":"Leah","last_name":"Ibbetson","email":"libbetsong@tinypic.com","gender":"Female","dob":"1999-01-06","weight":74},
{"first_name":"Ermentrude","last_name":"Magowan","email":"emagowanh@nymag.com","gender":"Female","dob":"1998-05-20","weight":85},
{"first_name":"Leonelle","last_name":"Pfaffe","email":"lpfaffei@state.gov","gender":"Female","dob":"2002-01-28","weight":79},
{"first_name":"Vicky","last_name":"Whitley","email":"vwhitleyj@japanpost.jp","gender":"Female","dob":"2001-01-07","weight":72},
{"first_name":"Kristyn","last_name":"Tatum","email":"ktatumk@e-recht24.de","gender":"Female","dob":"1998-01-23","weight":55},
{"first_name":"Gabby","last_name":"MacLaren","email":"gmaclarenl@sogou.com","gender":"Male","dob":"1995-12-27","weight":65},
{"first_name":"Drucie","last_name":"Leggett","email":"dleggettm@people.com.cn","gender":"Female","dob":"1998-03-10","weight":48},
{"first_name":"Carolee","last_name":"Backes","email":"cbackesn@amazon.co.jp","gender":"Female","dob":"2005-01-22","weight":87},
{"first_name":"Quincy","last_name":"Grim","email":"qgrimo@pbs.org","gender":"Male","dob":"1998-10-14","weight":70},
{"first_name":"Barret","last_name":"Chasmar","email":"bchasmarp@paypal.com","gender":"Male","dob":"2001-03-22","weight":65},
{"first_name":"Dermot","last_name":"Potell","email":"dpotellq@sphinn.com","gender":"Male","dob":"2005-04-26","weight":42},
{"first_name":"Flore","last_name":"Napleton","email":"fnapletonr@blogger.com","gender":"Female","dob":"2000-09-11","weight":60},
{"first_name":"Maynord","last_name":"Connew","email":"mconnews@illinois.edu","gender":"Male","dob":"2005-01-02","weight":81},
{"first_name":"Freemon","last_name":"Daout","email":"fdaoutt@ihg.com","gender":"Male","dob":"1999-11-26","weight":42},
{"first_name":"Port","last_name":"Gurge","email":"pgurgeu@meetup.com","gender":"Male","dob":"1998-05-16","weight":66},
{"first_name":"Sanford","last_name":"Gregh","email":"sgreghv@amazonaws.com","gender":"Male","dob":"2004-09-06","weight":82},
{"first_name":"Whitney","last_name":"Steers","email":"wsteersw@oakley.com","gender":"Male","dob":"2002-08-13","weight":88},
{"first_name":"Laurice","last_name":"Keynes","email":"lkeynesx@wired.com","gender":"Female","dob":"2001-10-04","weight":57},
{"first_name":"Tove","last_name":"Artingstall","email":"tartingstally@nationalgeographic.com","gender":"Female","dob":"1998-09-24","weight":75},
{"first_name":"Petronilla","last_name":"McCarlich","email":"pmccarlichz@reuters.com","gender":"Female","dob":"1996-04-08","weight":87},
{"first_name":"Nanette","last_name":"Izac","email":"nizac10@apache.org","gender":"Female","dob":"2002-10-09","weight":77},
{"first_name":"Murray","last_name":"McCann","email":"mmccann11@myspace.com","gender":"Male","dob":"1996-06-09","weight":68},
{"first_name":"Robers","last_name":"Sylvester","email":"rsylvester12@geocities.jp","gender":"Male","dob":"1998-01-09","weight":89},
{"first_name":"Jocko","last_name":"Allsep","email":"jallsep13@godaddy.com","gender":"Male","dob":"1997-06-03","weight":51},
{"first_name":"Naoma","last_name":"Sprankling","email":"nsprankling14@omniture.com","gender":"Female","dob":"2004-09-01","weight":86},
{"first_name":"Brandi","last_name":"Paver","email":"bpaver15@geocities.jp","gender":"Female","dob":"2001-03-15","weight":74},
{"first_name":"Andonis","last_name":"Spencelayh","email":"aspencelayh16@va.gov","gender":"Genderqueer","dob":"2005-07-21","weight":43},
{"first_name":"Magdalena","last_name":"Braben","email":"mbraben17@etsy.com","gender":"Female","dob":"1999-10-27","weight":45},
{"first_name":"William","last_name":"Romaine","email":"wromaine18@theglobeandmail.com","gender":"Male","dob":"1999-12-25","weight":83},
{"first_name":"Mora","last_name":"Cashford","email":"mcashford19@tinypic.com","gender":"Female","dob":"2004-10-28","weight":41},
{"first_name":"Neda","last_name":"Tersay","email":"ntersay1a@netlog.com","gender":"Female","dob":"2000-03-18","weight":74},
{"first_name":"Helen-elizabeth","last_name":"Dwelley","email":"hdwelley1b@statcounter.com","gender":"Female","dob":"2005-11-08","weight":90},
{"first_name":"Bekki","last_name":"Verbrugge","email":"bverbrugge1c@oaic.gov.au","gender":"Female","dob":"2002-03-03","weight":44},
{"first_name":"Errick","last_name":"Dayce","email":"edayce1d@joomla.org","gender":"Male","dob":"1998-05-31","weight":77},
{"first_name":"Paulo","last_name":"Geake","email":"pgeake1e@desdev.cn","gender":"Male","dob":"2004-10-03","weight":52},
{"first_name":"Shawn","last_name":"Semken","email":"ssemken1f@a8.net","gender":"Female","dob":"1996-07-04","weight":68},
{"first_name":"Aleta","last_name":"Padmore","email":"apadmore1g@yale.edu","gender":"Female","dob":"2003-02-24","weight":49},
{"first_name":"Issy","last_name":"Bletsoe","email":"ibletsoe1h@de.vu","gender":"Female","dob":"2002-11-14","weight":41},
{"first_name":"Lewiss","last_name":"Abdy","email":"labdy1i@dyndns.org","gender":"Male","dob":"2000-03-08","weight":77},
{"first_name":"Rodolph","last_name":"Orvis","email":"rorvis1j@rambler.ru","gender":"Male","dob":"2002-08-11","weight":46},
{"first_name":"Elvis","last_name":"Fishlock","email":"efishlock1k@utexas.edu","gender":"Male","dob":"2000-08-12","weight":40},
{"first_name":"Orland","last_name":"Deveraux","email":"odeveraux1l@elegantthemes.com","gender":"Male","dob":"2002-09-21","weight":54},
{"first_name":"Beckie","last_name":"Cosby","email":"bcosby1m@tiny.cc","gender":"Female","dob":"1995-12-24","weight":50},
{"first_name":"Vally","last_name":"Eardley","email":"veardley1n@addthis.com","gender":"Female","dob":"2003-10-31","weight":60},
{"first_name":"Bat","last_name":"Jager","email":"bjager1o@blogger.com","gender":"Male","dob":"2004-07-04","weight":70},
{"first_name":"Thaxter","last_name":"Kenningham","email":"tkenningham1p@nba.com","gender":"Male","dob":"1998-06-12","weight":70},
{"first_name":"Starlin","last_name":"Avramov","email":"savramov1q@ucoz.ru","gender":"Male","dob":"2004-12-20","weight":79},
{"first_name":"Hillard","last_name":"Ingray","email":"hingray1r@weather.com","gender":"Female","dob":"2002-03-12","weight":75},
{"first_name":"Sandy","last_name":"Bristoe","email":"sbristoe1s@ucla.edu","gender":"Male","dob":"2003-01-06","weight":52},
{"first_name":"Bernie","last_name":"Ottery","email":"bottery1t@nymag.com","gender":"Male","dob":"2004-09-27","weight":49},
{"first_name":"Fredi","last_name":"Turrill","email":"fturrill1u@prweb.com","gender":"Female","dob":"1998-02-21","weight":83},
{"first_name":"Moina","last_name":"Mattsson","email":"mmattsson1v@ameblo.jp","gender":"Female","dob":"2002-02-21","weight":67},
{"first_name":"Bekki","last_name":"McGill","email":"bmcgill1w@imdb.com","gender":"Female","dob":"2003-02-08","weight":63},
{"first_name":"Roderick","last_name":"Nund","email":"rnund1x@wikimedia.org","gender":"Male","dob":"2002-03-28","weight":81},
{"first_name":"Sim","last_name":"Extence","email":"sextence1y@homestead.com","gender":"Male","dob":"2000-05-02","weight":67},
{"first_name":"Wilt","last_name":"Bernaciak","email":"wbernaciak1z@51.la","gender":"Male","dob":"2002-10-05","weight":86},
{"first_name":"Pietro","last_name":"Reisenstein","email":"preisenstein20@google.cn","gender":"Male","dob":"1999-11-10","weight":75},
{"first_name":"Viola","last_name":"Warbys","email":"vwarbys21@wsj.com","gender":"Female","dob":"2003-08-06","weight":76},
{"first_name":"Northrop","last_name":"Merrison","email":"nmerrison22@fotki.com","gender":"Male","dob":"2001-04-05","weight":82},
{"first_name":"Ricky","last_name":"Cranney","email":"rcranney23@msn.com","gender":"Male","dob":"2005-06-29","weight":47},
{"first_name":"Elwira","last_name":"Albrook","email":"ealbrook24@usnews.com","gender":"Female","dob":"2001-03-29","weight":73},
{"first_name":"Lauritz","last_name":"Eassom","email":"leassom25@liveinternet.ru","gender":"Male","dob":"1999-01-24","weight":40},
{"first_name":"Gaultiero","last_name":"Glyde","email":"gglyde26@dmoz.org","gender":"Male","dob":"2000-10-18","weight":48},
{"first_name":"Deonne","last_name":"Scandrick","email":"dscandrick27@sakura.ne.jp","gender":"Female","dob":"2001-08-15","weight":41},
{"first_name":"Gratia","last_name":"Scutchings","email":"gscutchings28@miibeian.gov.cn","gender":"Non-binary","dob":"1997-09-25","weight":61},
{"first_name":"Lorry","last_name":"Harvard","email":"lharvard29@bloglines.com","gender":"Female","dob":"2004-07-22","weight":79},
{"first_name":"Eveleen","last_name":"Irlam","email":"eirlam2a@omniture.com","gender":"Female","dob":"2004-12-23","weight":76},
{"first_name":"Gerrie","last_name":"Mayoh","email":"gmayoh2b@digg.com","gender":"Non-binary","dob":"2002-05-03","weight":43},
{"first_name":"Margret","last_name":"Bracken","email":"mbracken2c@whitehouse.gov","gender":"Female","dob":"2001-09-13","weight":80},
{"first_name":"Asa","last_name":"Donativo","email":"adonativo2d@typepad.com","gender":"Male","dob":"2002-09-10","weight":88},
{"first_name":"Alf","last_name":"Rosser","email":"arosser2e@mtv.com","gender":"Male","dob":"2003-02-12","weight":56},
{"first_name":"Haywood","last_name":"Everton","email":"heverton2f@about.me","gender":"Male","dob":"2004-10-06","weight":50},
{"first_name":"Kenny","last_name":"Garlee","email":"kgarlee2g@redcross.org","gender":"Male","dob":"2004-12-22","weight":43},
{"first_name":"Saudra","last_name":"Windrass","email":"swindrass2h@oakley.com","gender":"Female","dob":"2001-12-29","weight":70},
{"first_name":"Nathalie","last_name":"Bownd","email":"nbownd2i@skyrock.com","gender":"Female","dob":"1997-12-04","weight":72},
{"first_name":"Bernetta","last_name":"Leil","email":"bleil2j@timesonline.co.uk","gender":"Female","dob":"1996-11-05","weight":76},
{"first_name":"Herman","last_name":"Cases","email":"hcases2k@cbc.ca","gender":"Male","dob":"2002-08-14","weight":83},
{"first_name":"Deeann","last_name":"Neno","email":"dneno2l@addthis.com","gender":"Female","dob":"2000-02-16","weight":63},
{"first_name":"Minni","last_name":"Lemm","email":"mlemm2m@youtu.be","gender":"Female","dob":"2003-12-24","weight":60},
{"first_name":"Deane","last_name":"Lantiff","email":"dlantiff2n@jalbum.net","gender":"Male","dob":"2003-09-14","weight":65},
{"first_name":"Vanny","last_name":"Bourley","email":"vbourley2o@cocolog-nifty.com","gender":"Female","dob":"2000-06-26","weight":76},
{"first_name":"Lora","last_name":"MacAndie","email":"lmacandie2p@google.pl","gender":"Female","dob":"1999-09-02","weight":59},
{"first_name":"Babara","last_name":"Harkins","email":"bharkins2q@pen.io","gender":"Female","dob":"2003-06-03","weight":63},
{"first_name":"Frank","last_name":"Cranage","email":"fcranage2r@liveinternet.ru","gender":"Female","dob":"2005-03-24","weight":67}]
        for customer in customers:
            Customer.objects.create(**customer)
        self.stdout.write(
            self.style.SUCCESS('Successfully closed imported customer data')
        )
